version: "3"

services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db

  app:
    build: ./server
    container_name: app
    ports:
      - "3333:3333"
    volumes:
      - ./server:/app
    environment:
      - MONGODB_URI=mongodb://root:password@mongodb:27017/products_app?authSource=admin

volumes:
  mongodb-data:
